version: "3.8"

x-common:
  &base-image
  build:
    dockerfile: Dockerfile
    context: .
  image: parser:latest
  restart: always
  env_file:
    - .env


services:
  web:
    build: .
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/link
    links:
      - chromedriver
    depends_on:
      - db

  chromedriver:
    image: selenium/standalone-chrome
    hostname: chromedriver:4444

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=link
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data:

