version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8008:8000
    links:
      - chromedriver
    depends_on:
      - db

  chromedriver:
    image: selenium/standalone-chrome
    hostname: chromedriver:4444

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  postgres_data:

#version: "3.8"
#
#services:
#  web:
#    build: .
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=link
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5432
##    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
#    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
#    volumes:
#      - .:/app
#    ports:
#      - 8008:8000
##    environment:
##      - DATABASE_URL=postgresql://postgres:postgres@db:5432/link
#    links:
#      - chromedriver
#    depends_on:
#      - db
#
#  chromedriver:
#    image: selenium/standalone-chrome
#    hostname: chromedriver:4444
#
#  db:
#    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
##    expose:
##      - 5432
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=link
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5432
#
#volumes:
#  postgres_data:
#
